In [1]:
import numpy as np

In [3]:
scalar = np.array([1])
scalar

array([1])

In [4]:
vector = np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [8]:
matrix = np.array([[0,1,3],
                   [3,4,5],
                   [6,7,8]])
matrix

array([[0, 1, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
matrix.shape

(3, 3)